name: HappyGhastWar
version: '1.0'
main: me.wang.happyGhastWar.HappyGhastWar
api-version: '1.21'
authors: [lao_wang]
description: 乐魂战
website: https://plugins.ngup.eu.org

depend: [Multiverse-Core]

commands:
  ghastwar:
    aliases:
      - 'gw'
  party:
    aliases:
      - 'pt'

permissions:
  party.*:
    default: true
    children:
      party.create: true
      party.invite: true
      party.accept: true
      party.decline: true
      party.leave: true
      party.kick: true
      party.transfer: true
      party.disband: true
      party.info: true
  party.create:
    default: true
  party.invite:
    default: true
  party.accept:
    default: true
  party.decline:
    default: true
  party.leave:
    default: true
  party.kick:
    default: true
  party.transfer:
    default: true
  party.disband:
    default: true
  party.info:
    default: true
  gw.*:
    default: true
    children:
      gw.admin: true
      gw.debug: true
  gw.admin:
    default: op
  gw.gui:
    default: true
  gw.leave:
    default: true
  gw.join:
    default: op
  gw.debug:
    default: true
    children:
      gw.debug.openupgradegui: true
  gw.debug.openupgradegui:
    default: true
